[11/Sep/2015 08:40:32] DEBUG [django.db.backends:89] (0.002) 
            SELECT c.relname, c.relkind
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('r', 'v')
                AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
                AND pg_catalog.pg_table_is_visible(c.oid); args=None
[11/Sep/2015 08:40:32] DEBUG [django.db.backends:89] (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[11/Sep/2015 08:40:54] DEBUG [django.db.backends:89] (0.028) SELECT "ohmgear_users_usertype"."id", "ohmgear_users_usertype"."user_type" FROM "ohmgear_users_usertype"; args=()
[11/Sep/2015 08:40:57] ERROR [django.request:256] Internal Server Error: /api/users/
Traceback (most recent call last):
  File "/home/sazid/.virtualenvs/vohmgear/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sazid/.virtualenvs/vohmgear/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sazid/.virtualenvs/vohmgear/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 85, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sazid/.virtualenvs/vohmgear/local/lib/python2.7/site-packages/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/home/sazid/.virtualenvs/vohmgear/local/lib/python2.7/site-packages/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/html/ohmgear/apps/users/views.py", line 83, in create
    if serializer.is_valid():
  File "/home/sazid/.virtualenvs/vohmgear/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 187, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/sazid/.virtualenvs/vohmgear/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 367, in run_validation
    value = self.to_internal_value(data)
  File "/home/sazid/.virtualenvs/vohmgear/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 402, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/var/www/html/ohmgear/apps/users/serializer.py", line 15, in validate_user_type
    if value.id == 1:
AttributeError: 'NoneType' object has no attribute 'id'
[11/Sep/2015 08:42:22] DEBUG [django.db.backends:89] (0.004) 
            SELECT c.relname, c.relkind
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('r', 'v')
                AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
                AND pg_catalog.pg_table_is_visible(c.oid); args=None
[11/Sep/2015 08:42:22] DEBUG [django.db.backends:89] (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[11/Sep/2015 08:43:26] DEBUG [django.db.backends:89] (0.002) 
            SELECT c.relname, c.relkind
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('r', 'v')
                AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
                AND pg_catalog.pg_table_is_visible(c.oid); args=None
[11/Sep/2015 08:43:26] DEBUG [django.db.backends:89] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
